name: Matrix Multpication CI

on: [push, pull_request]

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        
        - name: Set up CMake
          uses: jwlawson/actions-setup-cmake@v1
          
        - name: Set up Singularity
          uses: eWaterCycle/setup-singularity@v7
          with:
            # Version of singularity to setup
            singularity-version: 3.6.1
          
        - name: Cache
          uses: actions/cache@v4
          with:
            path: |
              build
              ~/.cache
            key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
            restore-keys: |
              ${{ runner.os }}-cmake-

        - name: Install dependencies
          run: sudo apt-get update && sudo apt-get install -y build-essential cmake libopenmpi-dev openmpi-bin

        - name: Create build directory
          run: mkdir -p build
        
        - name: Initialize submodule
          run: git submodule update --init --recursive

        - name: Configure CMake
          run: cmake -S . -B build
        
        - name: Build
          run: cmake --build build
        
        - name: Run Tests
          run: ctest --test-dir build

        - name: Build Singularity Image
          run:  singularity build --fakeroot MatMultiplication.sif Singularity.def
        
        - name: Run Singularity image
          run: singularity run MatMultiplication.sif

        - name: Upload Singularity image as artifact
          uses: actions/upload-artifact@v4
          with:
            name: matmultiplication-image
            path: MatMultiplication.sif
