name: Matrix Multpication CI

on: [push, pull_request]

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        
        - name: Set up CMake
          uses: jwlawson/actions-setup-cmake@v2
          
        - name: Set up Singularity
          uses: eWaterCycle/setup-singularity@v7
          with:
            singularity-version: 3.8.3
          
        - name: Cache
          uses: actions/cache@v4
          with:
            path: |
              build
              ~/.cache
            key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
            restore-keys: |
              ${{ runner.os }}-cmake-

        - name: Install dependencies
          run: sudo apt-get update && sudo apt-get install -y build-essential cmake libopenmpi-dev openmpi-bin

        - name: Create build directory
          run: mkdir -p build
        
        - name: Initialize submodule
          run: git submodule update --init --recursive

        - name: Configure CMake
          run: cmake -S . -B build
        
        - name: Build
          run: cmake --build build
        
        - name: Run Tests
          run: ctest --test-dir build

        - name: Build Singularity Image
          run:  singularity build --fakeroot MatMultiplication.sif Singularity.def
        
        - name: Run Singularity image
          run: singularity run MatMultiplication.sif
          
        - name: Save Singularity image
          uses: actions/upload-artifact@v4
          with:
            name: matmul-image
            path: MatMultiplication.sif

        - name: Share image to G100
          env:
            PW_CINECA: ${{ secrets.PW_CINECA }}
            HOST_CINECA: ${{ secrets.HOST_CINECA }}
          run: |
            sshpass -p "$PW_CINECA" scp -o StrictHostKeyChecking=no MatMultiplication.sif a08trb62@login.g100.cineca.it:/g100/home/usertrain/a08trb62/Step_2_DeMarchRaffaelliTaddei

        - name: Run image on G100
          env:
            PW_CINECA: ${{ secrets.PW_CINECA }}
            HOST_CINECA: ${{ secrets.HOST_CINECA }}
          run: |
            ssh-keygen -f "/home/runner/.ssh/known_hosts" -R "login.g100.cineca.it"
            sshpass -p "$PW_CINECA" ssh -o StrictHostKeyChecking=no a08trb62@login.g100.cineca.it 'cd /g100/home/usertrain/a08trb62/Step_2_DeMarchRaffaelliTaddei && git pull && sbatch slurm-job.sh && cat output.txt'




