name: Matrix Multpication CI

on: [push, pull_request]

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        
        - name: Set up CMake
          uses: jwlawson/actions-setup-cmake@v1

        - name: Install dependencies
          run: sudo apt-get update && sudo apt-get install -y build-essential cmake libopenmpi-dev openmpi-bin

        - name: Create build directory
          run: mkdir -p build

      - name: Configure CMake
          run: cmake -S . -B build
        
        - name: Build
          run: cmake --build build
        
        - name: Run Tests
          run: ctest --test-dir build