name: Matrix Multpication CI

on: [push, pull_request]

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Setup Cmake
          uses: jwlanwson/actions-setup-cmake@v1

        - name: Create build directory
          run: mkdir -p build

        - name: Configure CMake
          run: cmake -S . -B build
        
        - name: Build
          run: cmake --build build
        
        - name: Run Tests
          run: ctest --test-dir build