name: Matrix Multpication CI

on: [push, pull_request]

jobs:
    build: 
        runs-on: ubuntu-latest
        if: "github.actor != 'github-actions[bot]'"
        steps:
        - uses: actions/checkout@v4
        
        - name: Set up CMake
          uses: jwlawson/actions-setup-cmake@v2
          
        - name: Set up Singularity
          uses: eWaterCycle/setup-singularity@v7
          with:
            singularity-version: 3.8.3
          
        - name: Cache
          uses: actions/cache@v4
          with:
            path: |
              build
              ~/.cache
            key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
            restore-keys: |
              ${{ runner.os }}-cmake-

        - name: Install dependencies
          run: sudo apt-get update && sudo apt-get install -y build-essential cmake libopenmpi-dev openmpi-bin

        - name: Create build directory
          run: mkdir -p build
        
        - name: Initialize submodule
          run: git submodule update --init --recursive

        - name: Configure CMake
          run: cmake -S . -B build
        
        - name: Build
          run: cmake --build build
        
        - name: Run Tests
          run: ctest --test-dir build

        - name: Build Singularity Image
          run:  singularity build --fakeroot MatMultiplication.sif Singularity.def
        
        - name: Run Singularity image
          run: singularity run MatMultiplication.sif

        - name: Save Singularity image
          uses: actions/upload-artifact@v4
          with:
            name: matmul-image
            path: MatMultiplication.sif
            
        - name: Share image to G100
          uses: appleboy/scp-action@v0.1.7
          with:
            host: ${{ secrets.HOST_CINECA }}
            password: ${{ secrets.PW_CINECA }}
            port: 22
            source: MatMultiplication.sif
            target: /g100/home/usertrain/a08trb62




